name: Test Bun PowerShell DateTime

on:
  workflow_dispatch:

jobs:
  test-bun-powershell:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Bun
        shell: pwsh
        run: |
          iwr https://bun.sh/install.ps1 -Useb | iex

      - name: Add Bun to PATH
        shell: pwsh
        run: |
          echo "$HOME\.bun\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Test Process StartTime
        shell: pwsh
        run: |
          bun install && bun run src/config.ts
